-- ============================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS - CATÁLOGO SURIMPORTACIONES
-- ============================================================================
-- Sistema de catálogo de productos con financiación y gestión de combos
-- Fecha de generación: 2025-10-22
-- ============================================================================

-- ============================================================================
-- 1. EXTENSIONES Y CONFIGURACIÓN
-- ============================================================================

-- Habilitar extensiones necesarias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 2. TABLAS PRINCIPALES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 TABLA: lineas
-- Descripción: Líneas de productos (nivel superior en la jerarquía)
-- Jerarquía: Línea > Categoría > Producto
-- ----------------------------------------------------------------------------
CREATE TABLE public.lineas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    descripcion text not null,

    constraint lineas_pkey primary key (id),
    constraint lineas_descripcion_unique unique (descripcion)
);

COMMENT ON TABLE public.lineas IS 'Tabla de líneas de productos (nivel superior en la jerarquía Línea > Categoría > Producto)';
COMMENT ON COLUMN public.lineas.id IS 'Identificador único de la línea';
COMMENT ON COLUMN public.lineas.descripcion IS 'Nombre/descripción de la línea';
COMMENT ON COLUMN public.lineas.created_at IS 'Fecha de creación de la línea';

-- ----------------------------------------------------------------------------
-- 2.2 TABLA: categorias
-- Descripción: Categorías de productos (nivel medio en la jerarquía)
-- ----------------------------------------------------------------------------
CREATE TABLE public.categorias (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    descripcion text not null,
    fk_id_linea bigint null,

    constraint categorias_pkey primary key (id)
);

COMMENT ON TABLE public.categorias IS 'Tabla de categorías de productos (parte de la jerarquía Línea > Categoría > Producto)';
COMMENT ON COLUMN public.categorias.fk_id_linea IS 'Línea a la que pertenece esta categoría (opcional)';

-- ----------------------------------------------------------------------------
-- 2.3 TABLA: marcas
-- Descripción: Marcas de productos con logos opcionales
-- ----------------------------------------------------------------------------
CREATE TABLE public.marcas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    descripcion text not null,
    logo text null,

    constraint marcas_pkey primary key (id)
);

COMMENT ON TABLE public.marcas IS 'Marcas de productos con logos opcionales';

-- ----------------------------------------------------------------------------
-- 2.4 TABLA: productos
-- Descripción: Catálogo principal de productos con múltiples imágenes
-- ----------------------------------------------------------------------------
CREATE TABLE public.productos (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    descripcion text not null,
    descripcion_detallada text null,
    precio numeric(10,2) not null,
    codigo varchar(50) null,
    imagen text null,
    imagen_2 text null,
    imagen_3 text null,
    imagen_4 text null,
    imagen_5 text null,
    destacado boolean default false,
    activo boolean default true,
    tiene_stock boolean not null default true,
    aplica_todos_plan boolean default false,
    aplica_solo_categoria boolean default false,
    aplica_plan_especial boolean default false,
    fk_id_categoria bigint null,
    fk_id_marca bigint null,

    constraint productos_pkey primary key (id)
);

COMMENT ON TABLE public.productos IS 'Catálogo principal de productos con múltiples imágenes';
COMMENT ON COLUMN public.productos.tiene_stock IS 'Indica si el producto tiene stock disponible';
COMMENT ON COLUMN public.productos.aplica_todos_plan IS 'El producto se incluye automáticamente en todos los planes de financiación';
COMMENT ON COLUMN public.productos.aplica_solo_categoria IS 'El producto solo se incluye en planes según su categoría';
COMMENT ON COLUMN public.productos.aplica_plan_especial IS 'El producto requiere configuración especial de planes';

-- ----------------------------------------------------------------------------
-- 2.5 TABLA: planes_financiacion
-- Descripción: Planes de financiación con diferentes configuraciones
-- ----------------------------------------------------------------------------
CREATE TABLE public.planes_financiacion (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    nombre text not null,
    cuotas integer not null,
    recargo_porcentual numeric(5,2) null,
    recargo_fijo numeric(10,2) null,
    monto_minimo numeric(10,2) not null,
    monto_maximo numeric(10,2) null,
    anticipo_minimo numeric(5,2) null,
    anticipo_minimo_fijo numeric(10,2) null,
    activo boolean default true,

    constraint planes_financiacion_pkey primary key (id)
);

COMMENT ON TABLE public.planes_financiacion IS 'Planes de financiación con diferentes configuraciones';
COMMENT ON COLUMN public.planes_financiacion.anticipo_minimo IS 'Porcentaje de anticipo mínimo requerido (0-100)';
COMMENT ON COLUMN public.planes_financiacion.anticipo_minimo_fijo IS 'Monto fijo de anticipo mínimo requerido en pesos';

-- ----------------------------------------------------------------------------
-- 2.6 TABLA: planes_categorias
-- Descripción: Relación muchos-a-muchos entre planes y categorías
-- ----------------------------------------------------------------------------
CREATE TABLE public.planes_categorias (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    fk_id_plan bigint not null,
    fk_id_categoria bigint not null,

    constraint planes_categorias_pkey primary key (id),
    constraint planes_categorias_unique unique (fk_id_plan, fk_id_categoria)
);

COMMENT ON TABLE public.planes_categorias IS 'Relación muchos-a-muchos entre planes y categorías';

-- ----------------------------------------------------------------------------
-- 2.7 TABLA: productos_planes
-- Descripción: Productos asignados manualmente a planes específicos
-- ----------------------------------------------------------------------------
CREATE TABLE public.productos_planes (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    fk_id_producto bigint not null,
    fk_id_plan bigint not null,
    activo boolean default true,
    destacado boolean default false,

    constraint productos_planes_pkey primary key (id),
    constraint productos_planes_unique unique (fk_id_producto, fk_id_plan)
);

COMMENT ON TABLE public.productos_planes IS 'Productos asignados manualmente a planes específicos';

-- ----------------------------------------------------------------------------
-- 2.8 TABLA: productos_planes_default
-- Descripción: Asociaciones automáticas por reglas de negocio
-- ----------------------------------------------------------------------------
CREATE TABLE public.productos_planes_default (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    fk_id_producto bigint null,
    fk_id_plan bigint not null,
    fk_id_combo integer null,
    activo boolean default true,

    constraint productos_planes_default_pkey primary key (id),
    constraint productos_planes_default_unique unique (fk_id_producto, fk_id_plan)
);

COMMENT ON TABLE public.productos_planes_default IS 'Asociaciones automáticas por reglas de negocio';
COMMENT ON COLUMN public.productos_planes_default.fk_id_combo IS 'Referencia opcional al combo asociado con este plan de financiación';

-- ----------------------------------------------------------------------------
-- 2.9 TABLA: zonas
-- Descripción: Zonas geográficas para configuración regional
-- ----------------------------------------------------------------------------
CREATE TABLE public.zonas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    nombre text null,

    constraint zonas_pkey primary key (id)
);

COMMENT ON TABLE public.zonas IS 'Zonas geográficas para configuración regional';

-- ----------------------------------------------------------------------------
-- 2.10 TABLA: configuracion
-- Descripción: Configuración general del sistema
-- ----------------------------------------------------------------------------
CREATE TABLE public.configuracion (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    telefono text null,

    constraint configuracion_pkey primary key (id)
);

COMMENT ON TABLE public.configuracion IS 'Configuración general del sistema';

-- ----------------------------------------------------------------------------
-- 2.11 TABLA: configuracion_zonas
-- Descripción: Configuración específica por zona geográfica
-- ----------------------------------------------------------------------------
CREATE TABLE public.configuracion_zonas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    fk_id_zona bigint not null,
    telefono text not null,

    constraint configuracion_zonas_pkey primary key (id)
);

COMMENT ON TABLE public.configuracion_zonas IS 'Configuración específica por zona geográfica';

-- ----------------------------------------------------------------------------
-- 2.12 TABLA: configuracion_web
-- Descripción: Configuración visual para la aplicación web
-- ----------------------------------------------------------------------------
CREATE TABLE public.configuracion_web (
    id serial primary key,
    created_at timestamp with time zone default now(),

    -- Configuraciones Desktop
    logo_url text,
    logo_width integer default 200,
    logo_height integer default 60,

    appbar_height integer default 64,
    appbar_background_color varchar(7) default '#ffffff',
    appbar_text_color varchar(7) default '#000000',

    section_title_size integer default 24,
    section_subtitle_size integer default 18,
    section_text_size integer default 16,

    search_box_width integer default 400,
    search_box_height integer default 40,

    home_section_height integer default 500,

    -- Configuraciones Mobile
    mobile_logo_width integer default 150,
    mobile_logo_height integer default 45,

    mobile_appbar_height integer default 56,

    mobile_section_title_size integer default 20,
    mobile_section_subtitle_size integer default 16,
    mobile_section_text_size integer default 14,

    mobile_search_box_width integer default 300,
    mobile_search_box_height integer default 36,

    mobile_home_section_height integer default 300,

    -- Colores generales
    primary_color varchar(7) default '#0066cc',
    secondary_color varchar(7) default '#f8f9fa',
    accent_color varchar(7) default '#ff6b35',

    -- Tipografías
    font_family_primary varchar(100) default 'Inter, sans-serif',
    font_family_secondary varchar(100) default 'Roboto, sans-serif',

    -- Configuración Home Section
    home_display_plan_id integer,
    home_display_products_count integer default 12,
    home_display_category_filter integer,
    home_display_brand_filter integer,
    home_display_featured_only boolean default false,

    -- Configuraciones de secciones
    combos boolean default false,
    titulo_seccion_combos text default 'Combos Especiales',
    titulo_seccion_promos text default 'Promociones',
    titulo_seccion_destacados text default 'Productos Destacados',
    combos_subtitulo text null,

    -- Banners del home
    banner_1 text null,
    banner_2 text null,
    banner_3 text null
);

COMMENT ON TABLE configuracion_web IS 'Configuración visual para la aplicación web';
COMMENT ON COLUMN configuracion_web.logo_url IS 'URL del logo principal';
COMMENT ON COLUMN configuracion_web.logo_width IS 'Ancho del logo en desktop (px)';
COMMENT ON COLUMN configuracion_web.logo_height IS 'Alto del logo en desktop (px)';
COMMENT ON COLUMN configuracion_web.appbar_height IS 'Altura de la barra de navegación en desktop (px)';
COMMENT ON COLUMN configuracion_web.home_section_height IS 'Altura de la sección principal del home (px)';
COMMENT ON COLUMN configuracion_web.combos IS 'Habilitar o deshabilitar la sección de combos en la web';
COMMENT ON COLUMN configuracion_web.titulo_seccion_combos IS 'Título personalizable para la sección de combos';
COMMENT ON COLUMN configuracion_web.titulo_seccion_promos IS 'Título personalizable para la sección de promociones';
COMMENT ON COLUMN configuracion_web.titulo_seccion_destacados IS 'Título personalizable para la sección de productos destacados';
COMMENT ON COLUMN configuracion_web.combos_subtitulo IS 'Subtítulo opcional para la sección de combos';
COMMENT ON COLUMN configuracion_web.banner_1 IS 'URL o path de la primera imagen de banner para el home';
COMMENT ON COLUMN configuracion_web.banner_2 IS 'URL o path de la segunda imagen de banner para el home';
COMMENT ON COLUMN configuracion_web.banner_3 IS 'URL o path de la tercera imagen de banner para el home';

-- ============================================================================
-- 3. SISTEMA DE COMBOS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 TABLA: combos
-- Descripción: Tabla principal de combos de productos con precios calculados
-- ----------------------------------------------------------------------------
CREATE TABLE public.combos (
    id serial primary key,
    nombre varchar(255) not null,
    descripcion text,
    fecha_vigencia_inicio date,
    fecha_vigencia_fin date,
    descuento_porcentaje decimal(5,2) default 0 check (descuento_porcentaje >= 0 and descuento_porcentaje <= 100),
    precio_combo decimal(10,2) not null default 0,
    precio_original decimal(10,2) not null default 0,
    imagen text,
    imagen_2 text,
    imagen_3 text,
    imagen_4 text,
    imagen_5 text,
    activo boolean default true,
    fk_id_categoria integer null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

COMMENT ON TABLE combos IS 'Tabla principal de combos de productos con precios calculados automáticamente';
COMMENT ON COLUMN combos.precio_combo IS 'Precio final del combo con descuento aplicado (calculado automáticamente)';
COMMENT ON COLUMN combos.precio_original IS 'Suma de precios de productos sin descuento (calculado automáticamente)';
COMMENT ON COLUMN combos.descuento_porcentaje IS 'Porcentaje de descuento aplicado al combo (0-100)';
COMMENT ON COLUMN combos.fk_id_categoria IS 'Referencia a la categoría del combo (opcional)';

-- ----------------------------------------------------------------------------
-- 3.2 TABLA: combo_productos
-- Descripción: Relación N:N entre combos y productos con cantidad
-- ----------------------------------------------------------------------------
CREATE TABLE public.combo_productos (
    id serial primary key,
    fk_id_combo integer not null,
    fk_id_producto integer not null,
    cantidad integer default 1 check (cantidad > 0),
    precio_unitario decimal(10,2),
    created_at timestamp with time zone default now(),
    unique(fk_id_combo, fk_id_producto)
);

COMMENT ON TABLE combo_productos IS 'Relación N:N entre combos y productos con cantidad';
COMMENT ON COLUMN combo_productos.cantidad IS 'Cantidad del producto en el combo';
COMMENT ON COLUMN combo_productos.precio_unitario IS 'Precio del producto al momento de agregarlo (histórico)';

-- ============================================================================
-- 4. FOREIGN KEYS (RELACIONES ENTRE TABLAS)
-- ============================================================================

-- Relaciones de categorias
ALTER TABLE public.categorias
    ADD CONSTRAINT categorias_fk_id_linea_fkey
    FOREIGN KEY (fk_id_linea)
    REFERENCES public.lineas (id) ON DELETE SET NULL;

-- Relaciones de productos
ALTER TABLE public.productos
    ADD CONSTRAINT productos_fk_id_categoria_fkey
    FOREIGN KEY (fk_id_categoria)
    REFERENCES public.categorias (id) ON DELETE SET NULL;

ALTER TABLE public.productos
    ADD CONSTRAINT productos_fk_id_marca_fkey
    FOREIGN KEY (fk_id_marca)
    REFERENCES public.marcas (id) ON DELETE SET NULL;

-- Relaciones de planes_categorias
ALTER TABLE public.planes_categorias
    ADD CONSTRAINT planes_categorias_fk_id_plan_fkey
    FOREIGN KEY (fk_id_plan)
    REFERENCES public.planes_financiacion (id) ON DELETE CASCADE;

ALTER TABLE public.planes_categorias
    ADD CONSTRAINT planes_categorias_fk_id_categoria_fkey
    FOREIGN KEY (fk_id_categoria)
    REFERENCES public.categorias (id) ON DELETE CASCADE;

-- Relaciones de productos_planes
ALTER TABLE public.productos_planes
    ADD CONSTRAINT productos_planes_fk_id_producto_fkey
    FOREIGN KEY (fk_id_producto)
    REFERENCES public.productos (id) ON DELETE CASCADE;

ALTER TABLE public.productos_planes
    ADD CONSTRAINT productos_planes_fk_id_plan_fkey
    FOREIGN KEY (fk_id_plan)
    REFERENCES public.planes_financiacion (id) ON DELETE CASCADE;

-- Relaciones de productos_planes_default
ALTER TABLE public.productos_planes_default
    ADD CONSTRAINT productos_planes_default_fk_id_producto_fkey
    FOREIGN KEY (fk_id_producto)
    REFERENCES public.productos (id) ON DELETE CASCADE;

ALTER TABLE public.productos_planes_default
    ADD CONSTRAINT productos_planes_default_fk_id_plan_fkey
    FOREIGN KEY (fk_id_plan)
    REFERENCES public.planes_financiacion (id) ON DELETE CASCADE;

ALTER TABLE public.productos_planes_default
    ADD CONSTRAINT productos_planes_default_fk_id_combo_fkey
    FOREIGN KEY (fk_id_combo)
    REFERENCES public.combos (id) ON DELETE CASCADE;

-- Relaciones de configuracion_zonas
ALTER TABLE public.configuracion_zonas
    ADD CONSTRAINT configuracion_zonas_fk_id_zona_fkey
    FOREIGN KEY (fk_id_zona)
    REFERENCES public.zonas (id) ON DELETE CASCADE;

-- Relaciones de configuracion_web
ALTER TABLE public.configuracion_web
    ADD CONSTRAINT configuracion_web_home_display_plan_id_fkey
    FOREIGN KEY (home_display_plan_id)
    REFERENCES public.planes_financiacion(id);

ALTER TABLE public.configuracion_web
    ADD CONSTRAINT configuracion_web_home_display_category_filter_fkey
    FOREIGN KEY (home_display_category_filter)
    REFERENCES public.categorias(id);

ALTER TABLE public.configuracion_web
    ADD CONSTRAINT configuracion_web_home_display_brand_filter_fkey
    FOREIGN KEY (home_display_brand_filter)
    REFERENCES public.marcas(id);

-- Relaciones de combos
ALTER TABLE public.combos
    ADD CONSTRAINT combos_fk_id_categoria_fkey
    FOREIGN KEY (fk_id_categoria)
    REFERENCES public.categorias(id) ON DELETE SET NULL;

-- Relaciones de combo_productos
ALTER TABLE public.combo_productos
    ADD CONSTRAINT combo_productos_fk_id_combo_fkey
    FOREIGN KEY (fk_id_combo)
    REFERENCES public.combos(id) ON DELETE CASCADE;

ALTER TABLE public.combo_productos
    ADD CONSTRAINT combo_productos_fk_id_producto_fkey
    FOREIGN KEY (fk_id_producto)
    REFERENCES public.productos(id) ON DELETE CASCADE;

-- ============================================================================
-- 5. ÍNDICES PARA OPTIMIZACIÓN DE CONSULTAS
-- ============================================================================

-- Índices para líneas
CREATE INDEX lineas_descripcion_idx ON public.lineas (descripcion);

-- Índices para categorias
CREATE INDEX categorias_fk_id_linea_idx ON public.categorias (fk_id_linea) WHERE fk_id_linea IS NOT NULL;

-- Índices para productos
CREATE INDEX productos_activo_idx ON public.productos (activo);
CREATE INDEX productos_destacado_idx ON public.productos (destacado);
CREATE INDEX productos_tiene_stock_idx ON public.productos (tiene_stock);
CREATE INDEX productos_fk_id_categoria_idx ON public.productos (fk_id_categoria);
CREATE INDEX productos_fk_id_marca_idx ON public.productos (fk_id_marca);
CREATE INDEX productos_aplica_todos_plan_idx ON public.productos (aplica_todos_plan);
CREATE INDEX productos_aplica_solo_categoria_idx ON public.productos (aplica_solo_categoria);
CREATE INDEX productos_aplica_plan_especial_idx ON public.productos (aplica_plan_especial);
CREATE INDEX productos_codigo_idx ON public.productos (codigo);

-- Índices para imágenes de productos (solo cuando no son nulas)
CREATE INDEX productos_imagen_idx ON public.productos (imagen) WHERE imagen IS NOT NULL;
CREATE INDEX productos_imagen_2_idx ON public.productos (imagen_2) WHERE imagen_2 IS NOT NULL;
CREATE INDEX productos_imagen_3_idx ON public.productos (imagen_3) WHERE imagen_3 IS NOT NULL;
CREATE INDEX productos_imagen_4_idx ON public.productos (imagen_4) WHERE imagen_4 IS NOT NULL;
CREATE INDEX productos_imagen_5_idx ON public.productos (imagen_5) WHERE imagen_5 IS NOT NULL;

-- Índices para planes de financiación
CREATE INDEX planes_financiacion_activo_idx ON public.planes_financiacion (activo);
CREATE INDEX planes_financiacion_cuotas_idx ON public.planes_financiacion (cuotas);
CREATE INDEX planes_financiacion_monto_minimo_idx ON public.planes_financiacion (monto_minimo);
CREATE INDEX planes_financiacion_anticipo_minimo_idx ON public.planes_financiacion (anticipo_minimo);
CREATE INDEX planes_financiacion_anticipo_minimo_fijo_idx ON public.planes_financiacion (anticipo_minimo_fijo);

-- Índices para planes_categorias
CREATE INDEX planes_categorias_fk_id_plan_idx ON public.planes_categorias (fk_id_plan);
CREATE INDEX planes_categorias_fk_id_categoria_idx ON public.planes_categorias (fk_id_categoria);

-- Índices para productos_planes
CREATE INDEX productos_planes_fk_id_producto_idx ON public.productos_planes (fk_id_producto);
CREATE INDEX productos_planes_fk_id_plan_idx ON public.productos_planes (fk_id_plan);
CREATE INDEX productos_planes_activo_idx ON public.productos_planes (activo);
CREATE INDEX productos_planes_destacado_idx ON public.productos_planes (destacado);

-- Índices para productos_planes_default
CREATE INDEX productos_planes_default_fk_id_producto_idx ON public.productos_planes_default (fk_id_producto);
CREATE INDEX productos_planes_default_fk_id_plan_idx ON public.productos_planes_default (fk_id_plan);
CREATE INDEX productos_planes_default_activo_idx ON public.productos_planes_default (activo);
CREATE INDEX productos_planes_default_combo_idx ON public.productos_planes_default(fk_id_combo);

-- Índices para configuracion_zonas
CREATE INDEX configuracion_zonas_fk_id_zona_idx ON public.configuracion_zonas (fk_id_zona);

-- Índices para combos
CREATE INDEX idx_combos_activo ON public.combos(activo);
CREATE INDEX idx_combos_vigencia ON public.combos(fecha_vigencia_inicio, fecha_vigencia_fin);
CREATE INDEX idx_combos_categoria ON public.combos(fk_id_categoria);

-- Índices para combo_productos
CREATE INDEX idx_combo_productos_combo ON public.combo_productos(fk_id_combo);
CREATE INDEX idx_combo_productos_producto ON public.combo_productos(fk_id_producto);

-- ============================================================================
-- 6. FUNCIONES Y PROCEDIMIENTOS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 6.1 FUNCIÓN: update_updated_at_column
-- Descripción: Actualiza automáticamente el campo updated_at
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- ----------------------------------------------------------------------------
-- 6.2 FUNCIÓN: calcular_precio_combo
-- Descripción: Calcula el precio de un combo automáticamente
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.calcular_precio_combo(combo_id INTEGER)
RETURNS VOID AS $$
DECLARE
    precio_total DECIMAL(10,2) := 0;
    descuento DECIMAL(5,2);
    precio_final DECIMAL(10,2);
BEGIN
    -- Obtener el descuento del combo
    SELECT descuento_porcentaje INTO descuento
    FROM combos
    WHERE id = combo_id;

    -- Calcular precio total sumando los precios actuales de los productos
    SELECT COALESCE(SUM(p.precio * cp.cantidad), 0) INTO precio_total
    FROM combo_productos cp
    INNER JOIN productos p ON cp.fk_id_producto = p.id
    WHERE cp.fk_id_combo = combo_id;

    -- Aplicar descuento
    precio_final := precio_total * (1 - descuento / 100);

    -- Actualizar el combo
    UPDATE combos
    SET
        precio_original = precio_total,
        precio_combo = precio_final,
        updated_at = NOW()
    WHERE id = combo_id;

END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 6.3 FUNCIÓN: trigger_actualizar_precio_combo
-- Descripción: Trigger para actualizar precios cuando se modifica combo_productos
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trigger_actualizar_precio_combo()
RETURNS TRIGGER AS $$
BEGIN
    -- Actualizar precio del combo afectado
    IF TG_OP = 'DELETE' THEN
        PERFORM calcular_precio_combo(OLD.fk_id_combo);
        RETURN OLD;
    ELSE
        PERFORM calcular_precio_combo(NEW.fk_id_combo);
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 6.4 FUNCIÓN: trigger_actualizar_combos_por_producto
-- Descripción: Trigger para actualizar combos cuando cambia precio de producto
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trigger_actualizar_combos_por_producto()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo si cambió el precio
    IF NEW.precio != OLD.precio THEN
        -- Actualizar todos los combos que contengan este producto
        PERFORM calcular_precio_combo(cp.fk_id_combo)
        FROM combo_productos cp
        WHERE cp.fk_id_producto = NEW.id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 6.5 FUNCIÓN: trigger_actualizar_precio_por_descuento
-- Descripción: Trigger para actualizar precios cuando cambia descuento del combo
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trigger_actualizar_precio_por_descuento()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo si cambió el descuento
    IF NEW.descuento_porcentaje != OLD.descuento_porcentaje THEN
        PERFORM calcular_precio_combo(NEW.id);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 7. TRIGGERS
-- ============================================================================

-- Trigger para actualizar updated_at en planes_financiacion
CREATE TRIGGER update_planes_financiacion_updated_at
    BEFORE UPDATE ON public.planes_financiacion
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger para actualizar updated_at en combos
CREATE TRIGGER update_combos_updated_at
    BEFORE UPDATE ON public.combos
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger para actualizar precios cuando se agregan/quitan/modifican productos en combos
CREATE TRIGGER trigger_combo_productos_cambios
    AFTER INSERT OR UPDATE OR DELETE ON public.combo_productos
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_actualizar_precio_combo();

-- Trigger para actualizar precios de combos cuando cambia el precio de un producto
CREATE TRIGGER trigger_producto_precio_cambio
    AFTER UPDATE ON public.productos
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_actualizar_combos_por_producto();

-- Trigger para actualizar precios cuando cambia el descuento del combo
CREATE TRIGGER trigger_combo_descuento_cambio
    AFTER UPDATE ON public.combos
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_actualizar_precio_por_descuento();

-- ============================================================================
-- 8. ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Habilitar RLS en todas las tablas principales
ALTER TABLE public.lineas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marcas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planes_financiacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planes_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos_planes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos_planes_default ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zonas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_zonas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_web ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combo_productos ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 9. POLÍTICAS DE SEGURIDAD
-- ============================================================================

-- Políticas para líneas
CREATE POLICY "Permitir acceso completo a lineas"
    ON public.lineas FOR ALL USING (true);

-- Políticas para categorias
CREATE POLICY "Permitir acceso completo a categorias"
    ON public.categorias FOR ALL USING (true);

-- Políticas para marcas
CREATE POLICY "Permitir acceso completo a marcas"
    ON public.marcas FOR ALL USING (true);

-- Políticas para productos
CREATE POLICY "Permitir acceso completo a productos"
    ON public.productos FOR ALL USING (true);

-- Políticas para planes_financiacion
CREATE POLICY "Permitir acceso completo a planes_financiacion"
    ON public.planes_financiacion FOR ALL USING (true);

-- Políticas para planes_categorias
CREATE POLICY "Permitir acceso completo a planes_categorias"
    ON public.planes_categorias FOR ALL USING (true);

-- Políticas para productos_planes
CREATE POLICY "Permitir acceso completo a productos_planes"
    ON public.productos_planes FOR ALL USING (true);

-- Políticas para productos_planes_default
CREATE POLICY "Permitir acceso completo a productos_planes_default"
    ON public.productos_planes_default FOR ALL USING (true);

-- Políticas para zonas
CREATE POLICY "Permitir acceso completo a zonas"
    ON public.zonas FOR ALL USING (true);

-- Políticas para configuracion
CREATE POLICY "Permitir acceso completo a configuracion"
    ON public.configuracion FOR ALL USING (true);

-- Políticas para configuracion_zonas
CREATE POLICY "Permitir acceso completo a configuracion_zonas"
    ON public.configuracion_zonas FOR ALL USING (true);

-- Políticas para configuracion_web
CREATE POLICY "Permitir acceso completo a configuracion_web"
    ON public.configuracion_web FOR ALL USING (true);

-- Políticas para combos
CREATE POLICY "Permitir acceso completo a combos"
    ON public.combos FOR ALL USING (true);

-- Políticas para combo_productos
CREATE POLICY "Permitir acceso completo a combo_productos"
    ON public.combo_productos FOR ALL USING (true);

-- ============================================================================
-- 10. STORAGE BUCKETS (SUPABASE)
-- ============================================================================

-- Crear bucket de imágenes
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'imagenes',
    'imagenes',
    true,
    5242880, -- 5MB en bytes
    ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']
) ON CONFLICT (id) DO NOTHING;

-- Política para subir imágenes (público)
CREATE POLICY "Permitir subir imágenes públicamente"
    ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'imagenes');

-- Política para ver imágenes (público)
CREATE POLICY "Permitir ver imágenes públicamente"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'imagenes');

-- Política para actualizar imágenes (público)
CREATE POLICY "Permitir actualizar imágenes públicamente"
    ON storage.objects
    FOR UPDATE
    USING (bucket_id = 'imagenes');

-- Política para eliminar imágenes (público)
CREATE POLICY "Permitir eliminar imágenes públicamente"
    ON storage.objects
    FOR DELETE
    USING (bucket_id = 'imagenes');

-- ============================================================================
-- 11. DATOS INICIALES (OPCIONAL)
-- ============================================================================

-- Insertar configuración web por defecto
INSERT INTO public.configuracion_web (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================

-- Notas importantes:
-- 1. Este script crea toda la estructura de base de datos
-- 2. Incluye todas las tablas, relaciones, índices, funciones y triggers
-- 3. RLS está habilitado con políticas permisivas para desarrollo
-- 4. El sistema de combos calcula precios automáticamente
-- 5. Soporta jerarquía: Línea > Categoría > Producto
-- 6. Incluye configuración web personalizable
-- 7. Storage bucket configurado para imágenes hasta 5MB
